# Generated by Django 5.2.7 on 2025-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('age', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=11)),
                ('coach_name', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=3, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=3)),
                ('chest', models.JSONField(blank=True, default=list, null=True)),
                ('biceps', models.JSONField(blank=True, default=list, null=True)),
                ('triceps', models.JSONField(blank=True, default=list, null=True)),
                ('back', models.JSONField(blank=True, default=list, null=True)),
                ('abs', models.JSONField(blank=True, default=list, null=True)),
                ('shoulders', models.JSONField(blank=True, default=list, null=True)),
                ('legs', models.JSONField(blank=True, default=list, null=True)),
                ('meal_plan', models.JSONField(blank=True, default=list, null=True)),
                ('type', models.CharField(max_length=50)),
                ('situation', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
