# Generated by Django 5.1.7 on 2025-10-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
