# Generated by Django 5.1.7 on 2025-10-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_height_alter_player_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
