# Generated by Django 5.1.7 on 2025-11-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_player_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coach_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
