# Generated by Django 5.2.7 on 2025-11-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_player_coach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
