# Generated by Django 5.1.7 on 2025-11-02 18:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_url'),
        ),
    ]
