# Generated by Django 5.2.7 on 2025-11-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image_url',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
